#! /bin/sh

# reads colorscheme.
# . ~/.config/colors/colorscheme.sh

# starts apps tied to bspwm.
sxhkd &
polybar example &
# bspwm configuration.

bspc monitor eDP1 -n 0 -d I II III IV
bspc monitor HDMI1 -n 1 -d V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true
#bspc config window_gap 0

# rules.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating

# colors.
# following tomorrow-night theme: https://github.com/chriskempson/tomorrow-theme
#bspc config normal_border_color \#282a2e
#bspc config active_border_color \#373b41
#bspc config active_border_color \#282a2e
#bspc config focused_border_color \#f0c674
#bspc config focused_border_color \#D3D3D3
#bspc config presel_feedback_color \#f0c674
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"
